spring:
  application:
    name: lin-auth-api

  profiles:
    active: local

jwt:
  secret-key: ${JWT_SECRET_KEY:local-admin-authenticate-secret-key}
  expiration-minutes: 1200
  refresh-expiration-minutes: 10080
